feat: add squashfs with lvm support to install command

diff --git a/cmd/install/main b/cmd/install/main
--- a/cmd/install/main
+++ b/cmd/install/main
@@ -17,14 +17,19 @@ USAGE:
 
 OPTIONS:
   -h, --help                 print this menu
-  -d, --initramfs-dest       destination of the initramfs (default: /boot)
+  -i, --initramfs-dest       destination of the initramfs (default: /boot)
+  -d, --squashfs-dest        destination of the root squashfs filesystem (required)
+  -l, --resize-lvm           prevent root lvm logical volume resize (default: false)
 EOF
 }
 
 function clean_install {
   exit_code="$?"
+  log="log_info"
   if [ "$exit_code" != "0" ]; then
-    log_info "exit code $exit_code trapped, cleaning install..."
+    log="log_error"
+
+    log_error "exit code $exit_code trapped, cleaning install..."
   fi
 
   # Clean container if it exist
@@ -38,19 +43,35 @@ function clean_install {
     log_info "container $ctr removed"
   fi
 
-  log_info "install cleaned"
-
+  "$log" "install cleaned, exiting with status code of $exit_code"
   return $exit_code
+}
+
+function is_lvm_lv {
+  block="$(realpath $1)"
+  lvs="$(lvdisplay -c | egrep -o '/.*' | cut -s -d ':' -f 1)"
+
+  for lv in $lvs; do
+    if [ "$(realpath $lv)" = "$block" ]; then
+      echo "true"
+      return 0
+    fi
+  done
+
+  echo "false"
 }
 
 function install {
   local image_name="$1"
   local initramfs_dest="$2"
+  local rootfs_dest="$3"
+  local real_rootfs_dest="$(realpath $3)"
+  local resize_lvm="$4"
 
-  log_info "starting install of $image_name image at $initramfs_dest"
+  log_info "starting install of $image_name image"
 
   log_info "creating container for install..."
-  local ctr=$(buildah from "$image_name")
+  local ctr=$(buildah from --device $real_rootfs_dest:$real_rootfs_dest:rw "$image_name")
   log_info "container $ctr created"
 
   # Clean container on error
@@ -66,14 +87,40 @@ function install {
     kver="UNDETERMINED"
   fi
 
-  log_info "generating initramfs..."
+  log_info "generating initramfs at $initramfs_dest..."
   mkdir -p "$ctr_rootfs/$initramfs_dest"
   buildah run \
     --env HOSTNAME="$image_name" \
-    --mount=type=bind,source=$initramfs_dest,destination=/boot \
-    --mount=type=bind,source=/lib/modules,destination=/lib/modules \
-    "$ctr" "/bin/sh" "-c" "KVER=$kver IMAGE_NAME=$image_name /eli/mkinitramfs" > >(log_pipe "[BUILDAH] %s") 2>&1
+    --volume $initramfs_dest:/boot \
+    --volume /lib/modules:/lib/modules:ro \
+    "$ctr" "/bin/sh" "-c" "KVER=$kver IMAGE_NAME=$image_name /eli/mkinitramfs" > >(log_pipe "[BUILDAH] [INITRAMFS] %s") 2>&1
   log_info "initramfs generated"
+
+  log_info "adding grub entry..."
+  log_info "grub entry added"
+
+  if [ "$resize_lvm" = "true" ] && [ "$(is_lvm_lv $rootfs_dest)" = "true" ]; then
+    log_info "expanding rootfs logical volume..."
+    lvresize --quiet --yes --extents +100%FREE $rootfs_dest || true
+    log_info "rootfs logical volume expanded"
+  fi
+
+  log_info "installing root filesystem on $rootfs_dest..."
+  buildah run \
+    "$ctr" "/bin/sh" "-c" "mksquashfs / $real_rootfs_dest -noappend -e /proc /sys /run /dev" > >(log_pipe "[BUILDAH] [FSTAB] %s") 2>&1
+  log_info "root filesystem installed"
+
+  if [ "$resize_lvm" = "true" ] && [ "$(is_lvm_lv $rootfs_dest)" = "true" ]; then
+    log_info "shrinking rootfs logical volume..."
+    tmpdir="$(mktemp -d)"
+
+    mount "$rootfs_dest" "$tmpdir"
+    local size="$(df -h | tail -n +2 | tr -s ' ' | grep "$rootfs_dest" | cut -d ' ' -f 3)"
+    umount -l "$tmpdir"
+
+    lvresize --quiet --yes --size $size $rootfs_dest < <(echo "y") || true
+    log_info "rootfs logical volume shrinked"
+  fi
 }
 
 function main {
@@ -101,8 +148,9 @@ function main {
     esac
   done
 
-  action="install"
-  initramfs_dest="/boot"
+  local rootfs_dest=""
+  local initramfs_dest="/boot"
+  local resize_lvm="true"
 
   # Parse options
   while [ $# -gt 0 ]; do
@@ -112,10 +160,32 @@ function main {
         exit 0
         ;;
 
-      -d|--initramfs-dest)
+      -i|--initramfs-dest)
         shift
         initramfs_dest="$1"
+        if [ $# -eq 0 ]; then
+          log_error "missing --initramfs-dest option value"
+          stacktrace="false"
+          exit 1
+        fi
         shift
+        ;;
+
+      -d|--rootfs-dest)
+        shift
+        rootfs_dest="$1"
+        if [ $# -eq 0 ]; then
+          log_error "missing --rootfs-dest option value"
+          stacktrace="false"
+          exit 1
+        fi
+
+        shift
+        ;;
+
+      -l|--resize-lvm)
+        shift
+        resize_lvm="false"
         ;;
 
       *)
@@ -132,6 +202,13 @@ function main {
     exit 1
   fi
 
+  # Ensure rootfs block device file exist
+  if [ ! -b  "$rootfs_dest" ]; then
+    log_error "$rootfs_dest: no such block device"
+    stacktrace="false"
+    exit 1
+  fi
+
   # Ask for root permissions if not root
   if [ "$EUID" != "0" ]; then
     log_error "install require root permissions"
@@ -140,7 +217,7 @@ function main {
   fi
 
   for image in ${!images[@]}; do
-    "$action" "$image" "$initramfs_dest"
+    install "$image" "$initramfs_dest" "$rootfs_dest" "$resize_lvm"
   done
 }
 
