refacto: build command

diff --git a/cmd/build/dockerfile b/cmd/build/dockerfile
--- a/cmd/build/dockerfile
+++ b/cmd/build/dockerfile
@@ -1,8 +1,7 @@
 #!/usr/bin/env bash
 
-parent_dir="$(dirname $(readlink -e $0))"
-
-source "$parent_dir/../../lib/log"
+source "$ELI_PATH/lib/log"
+source "$ELI_PATH/lib/traps"
 
 if [ $# -eq 0 ]; then
   log_fatal "missing Dockerfile path"
@@ -10,9 +9,19 @@ fi
 
 dockerfile="$1"
 shift
+cd $(dirname "$dockerfile") 2>&1 > /dev/null
 
-buildah bud -f "$dockerfile" $@ 2>&1 > >(
-  while IFS= read -r line; do
-    log "[BUILDAH] %s" "$line"
-  done
-)
+log_info "starting to build $dockerfile..."
+
+set -e
+buildah bud -f "$(basename $dockerfile)" $@ > >(log_pipe "[BUILDAH] %s") 2>&1
+exit_code="$?"
+set +e
+
+cd - 2>&1 > /dev/null
+if [ "$exit_code" != "0" ]; then
+  log_error "build of $dockerfile failed"
+  exit $exit_code
+fi
+
+log_info "$dockerfile successfully built"
diff --git a/cmd/build/main b/cmd/build/main
--- a/cmd/build/main
+++ b/cmd/build/main
@@ -1,16 +1,19 @@
 #!/usr/bin/env bash
 
 parent_dir="$(dirname $(readlink -e $0))"
+source "$ELI_PATH/lib/log"
+source "$ELI_PATH/lib/traps"
 
-source "$parent_dir/../../lib/log"
+set -e
+trap exit_trap EXIT
 
 function print_help {
   cat <<EOF
 Build OCI images using efifiles or Dockerfiles
 
 USAGE:
-  $cmdname my/efifile my/efifile2 [elifile options] -- [buildah commit options]
-  $cmdname my/Dockerfile my/Dockerfile2 [buildah build options]
+  eli build my/efifile my/efifile2 [elifile options] -- [buildah commit options]
+  eli build my/Dockerfile my/Dockerfile2 [buildah build options]
 
 OPTIONS:
   -h, --help           print this menu
@@ -44,52 +47,74 @@ function is_dockerfile {
   fi
 }
 
-declare -A files
-declare -a options
+function main {
+  declare -A files
+  declare -a options
 
-while [ $# -gt 0 ]; do
-  case "$1" in
-    -*|--.*)
-      options+=("$1")
-      shift
+  # Parse build command options
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -h|--help)
+        print_help
+        exit 0
+        ;;
 
-      # Flag value
-      if [ "${1:0:1}" != "-" ]; then
+      *)
+        break
+        ;;
+    esac
+  done
+
+
+  # Parse buildah commit or buildah build options
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -*|--.*)
         options+=("$1")
         shift
-      fi
-      ;;
-    
-    *)
-      if [ "${#options[@]}" != "0" ]; then
-        log_error "files $1 is placed after options \"${options[@]}\", options must be placed after arguments"
-        exit 1
-      fi
 
-      files["$1"]="1"
-      shift
-      ;;
-  esac
-done
+        # Flag value
+        if [ "$1" != "" ] && [ "${1:0:1}" != "-" ]; then
+          options+=("$1")
+          shift
+        fi
+        ;;
+      
+      *)
+        if [ "${#options[@]}" != "0" ]; then
+          log_error "files $1 is placed after options \"${options[@]}\", options must be placed after files"
+          exit 1
+        fi
 
-if [ "${#files[@]}" = "0" ]; then
-  log_error "no file to build specified"
-  exit 1
-fi
+        files["$1"]="1"
+        shift
+        ;;
+    esac
+  done
 
-for file in "${!files[@]}"; do
-  if [ ! -f "$file" ]; then
-    log_error "build $file: no such file"
+  if [ "${#files[@]}" = "0" ]; then
+    log_error "no file to build specified"
     exit 1
   fi
 
-  if [ "$(is_dockerfile $file)" = "true" ]; then
-    source "$parent_dir/dockerfile" $file ${options[@]}
-  else
-    source "$parent_dir/elifile" $file ${options[@]}
-  fi
+  for file in "${!files[@]}"; do
+    if [ ! -f "$file" ]; then
+      log_error "build $file: no such file"
+      exit 1
+    fi
 
-  if [ "$?" != "0" ]; then
-    exit $?
-  fi
-done
+    if [ "$(is_dockerfile $file)" = "true" ]; then
+      source "$parent_dir/dockerfile" $file ${options[@]} || exit $?
+    else
+      source "$parent_dir/elifile" $file ${options[@]} || exit $?
+    fi
+
+    if [ "$?" != "0" ]; then
+      log_error "build of $file failed"
+      stacktrace="false"
+      exit $?
+    fi
+  done
+}
+
+main "$@"
